### PR TITLE
add name

### PR DESCRIPTION
**Pull request by efinit**
added my name

### CODE REVIEW

**Comment by bmneely** [comment]
@efinit  it looks like there is a merge conflict between your master branch and the upstream master. Another student changed the file, so your PR is now out of date. Don't worry, this is easy to fix (and great to learn)!

If you haven't already, you'll need to add an `upstream` remote to your local repo. From your computer in your fullstack-example-collaboration folder:

```
$ git remote add upstream https://github.com/Bloc/fullstack-example-collaboration-repo
```

Then pull down the changes from upstream:
```
$ git pull upstream master
````

You might have to resolve [merge conflicts](https://help.github.com/articles/resolving-merge-conflicts/) between your changes and the upstream changes.

After you resolve the merge conflict, add, commit, and push your changes back up to your own repo (`origin`). This will automatically update the PR and it will be good to merge! Just write a comment mentioning @bmneely to let me know.

Good luck, if you have any questions, don't hesitate to reach out to me or your mentor!

**Comment by efinit** [comment]
@bmneely I added the upstream and pulled down the changes, but when I'm stuck on resolving the merge conflicts. That link wasn't very helpful. Can you help?

**Comment by efinit** [comment]
@bmneely So, I chatted with my mentor and it should be good to go. Let me know if I need to do something else, or if I'm gonna have more hair to pull out!

**Comment by bmneely** [comment]
@efinit after you pull down the changes, you'll need to push them up to your repository so that when you go to your GitHub account and look at the repo, it doesn't say that you're any commits behind Bloc:master: https://www.dropbox.com/s/2ioh7gg3ut7kb0i/Screenshot%202015-03-30%2009.04.50.png?dl=0

**Comment by efinit** [comment]
@bmneely I'm confused, sir. My mentor told me there wasn't anything else to do with what we did to fix the issue. Granted, the explanation of what happened was vague, so I'm a little (a lot) lost.

**Comment by bmneely** [comment]
Once you've pulled down the upstream commits and resolved the merge conflict (you'll need to pull down against since the upstream has been modified recently) you then need *push* those changes to your GitHub repo so that that PR is updated. Right now your PR only has one commit, becuase you haven't pushed the changes up to your repo. To push them, just do:

```bash
$ git push origin master
```

after you pull down and resolve the merge conflict.

**Comment by efinit** [comment]
@bmneely When you say pull down upstream commits and resolved the merge conflict, how do I go back to what I did to resolve the merge conflict and pull down the upstream commits? I've done it once and don't really recall what the hell I did. I have no grasp of the whole pull, push and commit process, so pardon me if I'm asking for step-by-step instructions. Right now you're speaking fluent Chinese to someone with a translation app and I can't follow along well enough to type what you're saying into my app (if that's a good analogy). Thanks!

**Comment by efinit** [comment]
@bmneely So I tried to figure out the whole push, pull stuff and here's what I did. I still don't see the commit updated on github, so please tell me what I'm missing:
```
Eric-Patinos-MacBook-Pro:~ efinit$ cd fullstack-example-collaboration-repo
Eric-Patinos-MacBook-Pro:fullstack-example-collaboration-repo efinit$ cd
Eric-Patinos-MacBook-Pro:~ efinit$ cd fullstack-example-collaboration-repo
Eric-Patinos-MacBook-Pro:fullstack-example-collaboration-repo efinit$ git remote -v
origin	https://github.com/efinit/fullstack-example-collaboration-repo.git (fetch)
origin	https://github.com/efinit/fullstack-example-collaboration-repo.git (push)
Eric-Patinos-MacBook-Pro:fullstack-example-collaboration-repo efinit$ git remote add upstream git@github.com:efinit/fullstack-example-collaboration-repo.git
Eric-Patinos-MacBook-Pro:fullstack-example-collaboration-repo efinit$ git remote -v
origin	https://github.com/efinit/fullstack-example-collaboration-repo.git (fetch)
origin	https://github.com/efinit/fullstack-example-collaboration-repo.git (push)
upstream	git@github.com:efinit/fullstack-example-collaboration-repo.git (fetch)
upstream	git@github.com:efinit/fullstack-example-collaboration-repo.git (push)
Eric-Patinos-MacBook-Pro:fullstack-example-collaboration-repo efinit$ git pull upstream master
The authenticity of host 'github.com (192.30.252.130)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.130' (RSA) to the list of known hosts.
remote: Counting objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 2
Unpacking objects: 100% (3/3), done.
From github.com:efinit/fullstack-example-collaboration-repo
 * branch            master     -> FETCH_HEAD
Updating 30a403e..2d02671
Fast-forward
 README.md |    1 +
 1 files changed, 1 insertions(+), 0 deletions(-)
Eric-Patinos-MacBook-Pro:fullstack-example-collaboration-repo efinit$ git push origin master
Username: 
Password: 
Everything up-to-date
Eric-Patinos-MacBook-Pro:fullstack-example-collaboration-repo efinit$ 
```

**Comment by efinit** [comment]
@bmneely I also tried to 'Propose file changes' on the commit on github but that green button is inactive. I really wish I could figure this out on my own because I know in your eyes this is simple shit. Sorry.

**Pull request closed without merging**
